version: "3.9"
services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: "task_manager"
      POSTGRES_USER: "task_user"
      POSTGRES_PASSWORD: "Vrangel123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
