# Generated by Django 4.1.7 on 2023-02-18 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="status",
            old_name="value",
            new_name="name",
        ),
        migrations.AddField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
